# Generated by Django 5.2.17 on 2026-08-28 05:16

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('region', models.CharField(max_length=100)),
                ('destination_city', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('sla_hours', models.IntegerField(default=24)),
                ('avg_volume', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Mechanical', 'Mechanical'), ('Polymers', 'Polymers'), ('Fasteners', 'Fasteners'), ('Powertrain', 'Powertrain'), ('Optical', 'Optical'), ('General', 'General')], default='General', max_length=50)),
                ('stock_on_hand', models.IntegerField(default=0)),
                ('safety_stock', models.IntegerField(default=0)),
                ('turnover_ratio', models.FloatField(default=1.0)),
                ('movement_velocity', models.CharField(choices=[('Fast', 'Fast'), ('Medium', 'Medium'), ('Slow', 'Slow'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('efficiency_gain', models.CharField(max_length=50)),
                ('impact_metric', models.CharField(max_length=100)),
                ('action_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('applied', 'Applied & Dispatched'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('supervisor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('dispatched_details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_name', models.CharField(max_length=150)),
                ('volume_shock_pct', models.FloatField(default=0.0)),
                ('absenteeism_pct', models.FloatField(default=0.0)),
                ('transit_delay_hours', models.FloatField(default=0.0)),
                ('dock_congestion_risk', models.FloatField(default=0.0)),
                ('sla_breach_risk', models.FloatField(default=0.0)),
                ('bottleneck_index', models.FloatField(default=0.0)),
                ('unit_cost_impact', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('origin_city', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('item_type', models.CharField(max_length=100)),
                ('volume_history', models.FloatField(default=0.0)),
                ('lead_time_days', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dock_warning_threshold', models.IntegerField(default=85)),
                ('safety_stock_min_pct', models.IntegerField(default=20)),
                ('sla_target_compliance', models.IntegerField(default=95)),
                ('dark_mode', models.BooleanField(default=True)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('supervisor_contact', api.models.EncryptedCharField(default='supervisor.ops@oasis-system.org', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkforceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', api.models.EncryptedCharField(max_length=500)),
                ('primary_skill', models.CharField(max_length=100)),
                ('secondary_skill', models.CharField(blank=True, max_length=100)),
                ('efficiency_score', models.FloatField(default=0.85)),
                ('shift', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Night', 'Night')], default='Morning', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
