# Generated by Django 5.2.17 on 2026-08-28 05:50

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('storage_capacity_sqft', models.IntegerField(default=500000)),
                ('dock_doors', models.IntegerField(default=16)),
                ('operating_status', models.CharField(default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='recommendationrecord',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systempreference',
            name='facility_code',
            field=models.CharField(default='FAC-ALPHA-2026', max_length=50),
        ),
        migrations.AddField(
            model_name='systempreference',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systempreference',
            name='org_name',
            field=models.CharField(default='OASIS Global Logistics Corp', max_length=200),
        ),
        migrations.AlterField(
            model_name='systempreference',
            name='supervisor_contact',
            field=api.models.EncryptedCharField(default='plant.manager@oasis-system.org', max_length=500),
        ),
        migrations.AddField(
            model_name='customer',
            name='assigned_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='api.warehouse'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='assigned_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='api.warehouse'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='assigned_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='api.warehouse'),
        ),
        migrations.AddField(
            model_name='workforcemember',
            name='assigned_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workforce_members', to='api.warehouse'),
        ),
    ]
